export const TOP_RESULTS = 5;
export const SITE_RESULTS_CACHE_KEY = "siteResultsCacheV2";
export const SITE_RESULTS_TTL_MS = 5 * 60 * 1000;
export const GITHUB_FETCH_CONCURRENCY = 8;
export const SKILL_STATS_FETCH_CONCURRENCY = 6;
export const LIVE_STATS_CANDIDATE_LIMIT = 15;
export const MAX_KEYWORD_WORDS = 2;
export const MAX_TITLE_SEGMENT_FOR_KEYWORD = 40;
export const GA4_MEASUREMENT_ID = "G-SL64MDBERC";
export const GA4_API_SECRET = "okRF2BsIRlSYOwLsBnidPQ";
export const GA4_ENDPOINT_URL = "https://www.google-analytics.com/mp/collect";

export const INFRASTRUCTURE_SUBDOMAIN_LABELS = new Set([
  "app",
  "apps",
  "dev",
  "development",
  "eu",
  "internal",
  "k8s",
  "prod",
  "production",
  "staging",
  "stage",
  "test",
  "uat",
  "us"
]);

export const SELF_HOSTED_SERVICE_SUBDOMAIN_LABELS = new Set([
  "airflow",
  "argocd",
  "consul",
  "grafana",
  "jaeger",
  "jenkins",
  "keycloak",
  "kibana",
  "metabase",
  "minio",
  "nexus",
  "nomad",
  "prometheus",
  "sentry",
  "sonarqube",
  "superset",
  "temporal",
  "vault"
]);

export const KNOWN_HOSTNAME_KEYWORD_MAP = {
  "ai.google.dev": "google labs",
  "analytics.google.com": "google analytics",
  "anthropic.com": "anthropic",
  "api.github.com": "github",
  "app.datadoghq.com": "datadog",
  "apollo.io": "apollo",
  "apollographql.com": "apollo graphql",
  "aws.amazon.com": "aws",
  "calendar.google.com": "google calendar",
  "coderabbit.ai": "coderabbit",
  "datadoghq.com": "datadog",
  "deno.land": "deno",
  "docs.google.com": "google docs",
  "drive.google.com": "google drive",
  "firebase.google.com": "firebase",
  "gemini.google.com": "google gemini",
  "getdbt.com": "dbt",
  "github.com": "github",
  "exploreomni.com": "omni",
  "kotlinlang.org": "kotlin",
  "mail.google.com": "gmail",
  "meet.google.com": "google meet",
  "mcp-use.com": "mcp use",
  "neon.tech": "neon",
  "notion.com": "notion",
  "opensea.io": "opensea",
  "reactnative.dev": "reactnative",
  "sentry.io": "sentry",
  "sheets.google.com": "google sheets",
  "slides.google.com": "google slides",
  "trigger.dev": "trigger"
};

export const OFFICIAL_SKILLS_OWNER_HANDLES = [
  "anthropics",
  "apify",
  "apollographql",
  "astronomer",
  "auth0",
  "automattic",
  "axiomhq",
  "base",
  "better-auth",
  "bitwarden",
  "box",
  "brave",
  "browser-use",
  "browserbase",
  "callstackincubator",
  "clerk",
  "clickhouse",
  "cloudflare",
  "coderabbitai",
  "coinbase",
  "contentful",
  "contentstack",
  "dagster-io",
  "dash0hq",
  "datadog-labs",
  "dbt-labs",
  "deepgram",
  "denoland",
  "elevenlabs",
  "encoredev",
  "exploreomni",
  "expo",
  "facebook",
  "factory-ai",
  "figma",
  "firebase",
  "firecrawl",
  "flutter",
  "getsentry",
  "github",
  "google-gemini",
  "google-labs-code",
  "hashicorp",
  "huggingface",
  "kotlin",
  "langchain-ai",
  "langfuse",
  "launchdarkly",
  "livekit",
  "makenotion",
  "mapbox",
  "mastra-ai",
  "mcp-use",
  "medusajs",
  "microsoft",
  "n8n-io",
  "neondatabase",
  "nuxt",
  "openai",
  "openshift",
  "parallel-web",
  "pinecone-io",
  "planetscale",
  "posthog",
  "prisma",
  "projectopensea",
  "pulumi",
  "pytorch",
  "redis",
  "remotion-dev",
  "resend",
  "rivet-dev",
  "runwayml",
  "sanity-io",
  "semgrep",
  "shopify",
  "signoz",
  "streamlit",
  "stripe",
  "supabase",
  "sveltejs",
  "tavily-ai",
  "temporalio",
  "tinybirdco",
  "tldraw",
  "triggerdotdev",
  "upstash",
  "vercel",
  "vercel-labs",
  "webflow",
  "whopio",
  "wix",
  "wordpress"
];

export const OFFICIAL_SITE_KEYWORD_TEST_CASES = [
  ["https://anthropic.com", "Anthropic", "anthropic"],
  ["https://apify.com", "Apify", "apify"],
  ["https://apollographql.com", "Apollo GraphQL", "apollo graphql"],
  ["https://astronomer.io", "Astronomer", "astronomer"],
  ["https://auth0.com", "Auth0", "auth0"],
  ["https://automattic.com", "Automattic", "automattic"],
  ["https://axiom.co", "Axiom", "axiom"],
  ["https://base.org", "Base", "base"],
  ["https://better-auth.com", "Better Auth", "better auth"],
  ["https://bitwarden.com", "Bitwarden", "bitwarden"],
  ["https://box.com", "Box", "box"],
  ["https://brave.com", "Brave", "brave"],
  ["https://browser-use.com", "Browser Use", "browser use"],
  ["https://browserbase.com", "Browserbase", "browserbase"],
  ["https://callstack.com", "Callstack", "callstack"],
  ["https://clerk.com", "Clerk", "clerk"],
  ["https://clickhouse.com", "ClickHouse", "clickhouse"],
  ["https://cloudflare.com", "Cloudflare", "cloudflare"],
  ["https://coderabbit.ai", "CodeRabbit", "coderabbit"],
  ["https://coinbase.com", "Coinbase", "coinbase"],
  ["https://contentful.com", "Contentful", "contentful"],
  ["https://contentstack.com", "Contentstack", "contentstack"],
  ["https://dagster.io", "Dagster", "dagster"],
  ["https://dash0.com", "Dash0", "dash0"],
  ["https://datadoghq.com", "Datadog", "datadog"],
  ["https://getdbt.com", "dbt Labs", "dbt"],
  ["https://deepgram.com", "Deepgram", "deepgram"],
  ["https://deno.land", "Deno", "deno"],
  ["https://elevenlabs.io", "ElevenLabs", "elevenlabs"],
  ["https://encore.dev", "Encore", "encore"],
  ["https://exploreomni.com", "Omni Analytics", "omni"],
  ["https://expo.dev", "Expo", "expo"],
  ["https://reactnative.dev", "React Native", "reactnative"],
  ["https://factory.ai", "Factory", "factory"],
  ["https://figma.com", "Figma", "figma"],
  ["https://firebase.google.com", "Firebase", "firebase"],
  ["https://firecrawl.dev", "Firecrawl", "firecrawl"],
  ["https://flutter.dev", "Flutter", "flutter"],
  ["https://sentry.io", "Sentry", "sentry"],
  ["https://github.com", "GitHub", "github"],
  ["https://gemini.google.com", "Google Gemini", "google gemini"],
  ["https://ai.google.dev", "Google AI Studio", "google labs"],
  ["https://hashicorp.com", "HashiCorp", "hashicorp"],
  ["https://huggingface.co", "Hugging Face", "huggingface"],
  ["https://kotlinlang.org", "Kotlin", "kotlin"],
  ["https://langchain.com", "LangChain", "langchain"],
  ["https://langfuse.com", "Langfuse", "langfuse"],
  ["https://launchdarkly.com", "LaunchDarkly", "launchdarkly"],
  ["https://livekit.io", "LiveKit", "livekit"],
  ["https://notion.com", "Notion", "notion"],
  ["https://mapbox.com", "Mapbox", "mapbox"],
  ["https://mastra.ai", "Mastra", "mastra"],
  ["https://mcp-use.com", "mcp-use", "mcp use"],
  ["https://medusajs.com", "Medusa", "medusajs"],
  ["https://microsoft.com", "Microsoft", "microsoft"],
  ["https://n8n.io", "n8n", "n8n"],
  ["https://neon.tech", "Neon", "neon"],
  ["https://nuxt.com", "Nuxt", "nuxt"],
  ["https://openai.com", "OpenAI", "openai"],
  ["https://openshift.com", "OpenShift", "openshift"],
  ["https://parallel.ai", "Parallel", "parallel"],
  ["https://pinecone.io", "Pinecone", "pinecone"],
  ["https://planetscale.com", "PlanetScale", "planetscale"],
  ["https://posthog.com", "PostHog", "posthog"],
  ["https://prisma.io", "Prisma", "prisma"],
  ["https://opensea.io", "OpenSea", "opensea"],
  ["https://pulumi.com", "Pulumi", "pulumi"],
  ["https://pytorch.org", "PyTorch", "pytorch"],
  ["https://redis.io", "Redis", "redis"],
  ["https://remotion.dev", "Remotion", "remotion"],
  ["https://resend.com", "Resend", "resend"],
  ["https://rivet.dev", "Rivet", "rivet"],
  ["https://runwayml.com", "Runway", "runwayml"],
  ["https://sanity.io", "Sanity", "sanity"],
  ["https://semgrep.dev", "Semgrep", "semgrep"],
  ["https://shopify.com", "Shopify", "shopify"],
  ["https://signoz.io", "SigNoz", "signoz"],
  ["https://streamlit.io", "Streamlit", "streamlit"],
  ["https://stripe.com", "Stripe", "stripe"],
  ["https://supabase.com", "Supabase", "supabase"],
  ["https://svelte.dev", "Svelte", "svelte"],
  ["https://tavily.com", "Tavily", "tavily"],
  ["https://temporal.io", "Temporal", "temporal"],
  ["https://tinybird.co", "Tinybird", "tinybird"],
  ["https://tldraw.com", "tldraw", "tldraw"],
  ["https://trigger.dev", "Trigger.dev", "trigger"],
  ["https://upstash.com", "Upstash", "upstash"],
  ["https://vercel.com", "Vercel", "vercel"],
  ["https://webflow.com", "Webflow", "webflow"],
  ["https://whop.com", "Whop", "whop"],
  ["https://wix.com", "Wix", "wix"],
  ["https://wordpress.org", "WordPress", "wordpress"],
  ["https://aws.amazon.com", "Amazon Web Services", "aws"],
  ["https://analytics.google.com", "Google Analytics", "google analytics"],
  ["https://metabase.k8s.blockscout.com", "Metabase", "metabase"],
  ["https://eth.blockscout.com", "Blockscout", "blockscout"],
  ["https://eu.mixpanel.com/project/2824165/view/3358305/app/boards", "Boards - Mixpanel", "mixpanel"]
];

export const KEYWORD_OWNER_ALIAS_MAP = {
  "apollo graphql": ["apollographql"],
  aws: ["aws", "amazon", "amazonwebservices"],
  anthropic: ["anthropics"],
  atlassian: ["atlassian"],
  axiom: ["axiomhq"],
  "better auth": ["better-auth"],
  "browser use": ["browser-use"],
  callstack: ["callstackincubator"],
  cloudflare: ["cloudflare"],
  confluence: ["atlassian"],
  coderabbit: ["coderabbitai"],
  dagster: ["dagster-io"],
  dash0: ["dash0hq"],
  datadog: ["datadog-labs"],
  dbt: ["dbt-labs"],
  deno: ["denoland"],
  encore: ["encoredev"],
  factory: ["factory-ai"],
  figma: ["figma"],
  github: ["github"],
  gmail: ["googleworkspace"],
  google: ["googleworkspace"],
  "google analytics": ["googleanalytics", "googleworkspace"],
  "google calendar": ["googleworkspace"],
  "google docs": ["googleworkspace"],
  "google drive": ["googleworkspace"],
  "google gemini": ["google-gemini"],
  "google labs": ["google-labs-code"],
  "google meet": ["googleworkspace"],
  "google sheets": ["googleworkspace"],
  "google slides": ["googleworkspace"],
  huggingface: ["huggingface"],
  jira: ["atlassian"],
  langchain: ["langchain-ai"],
  linear: ["linear", "linearapp"],
  mastra: ["mastra-ai"],
  "mcp use": ["mcp-use"],
  medusajs: ["medusajs"],
  n8n: ["n8n-io"],
  neon: ["neondatabase"],
  notion: ["notionhq", "notion", "makenotion"],
  omni: ["exploreomni"],
  openai: ["openai"],
  opensea: ["projectopensea"],
  parallel: ["parallel-web"],
  pinecone: ["pinecone-io"],
  reactnative: ["facebook"],
  remotion: ["remotion-dev"],
  rivet: ["rivet-dev"],
  sanity: ["sanity-io"],
  sentry: ["getsentry"],
  shopify: ["shopify"],
  slack: ["slackapi", "slackhq", "slack"],
  stripe: ["stripe"],
  supabase: ["supabase"],
  svelte: ["sveltejs"],
  tavily: ["tavily-ai"],
  temporal: ["temporalio"],
  tinybird: ["tinybirdco"],
  trigger: ["triggerdotdev"],
  vercel: ["vercel", "vercel-labs"],
  whop: ["whopio"]
};

export const COMMON_TITLE_WORDS = new Set([
  "account",
  "app",
  "dashboard",
  "docs",
  "document",
  "home",
  "login",
  "page",
  "settings",
  "welcome"
]);

export const GENERIC_KEYWORD_PHRASES = new Set([
  "agent skills",
  "skills directory",
  "agent skills directory"
]);
